# Generated by Django 4.0.5 on 2022-06-24 22:09

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('check_in', models.CharField(default='false', max_length=20)),
                ('check_out', models.CharField(default='false', max_length=20)),
                ('profile_image_1', models.ImageField(null=True, upload_to=face.models.upload_to)),
                ('profile_image_2', models.ImageField(null=True, upload_to=face.models.upload_to)),
                ('employee_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
