# Generated by Django 4.0.5 on 2022-06-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_student_role_teacher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
