# Generated by Django 4.0.5 on 2022-06-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_student_user_id_teacher_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
