# Generated by Django 4.0.5 on 2022-06-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_uploadimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
