# Generated by Django 4.0.5 on 2022-06-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_rename_image_uploadimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('is_check_in', models.CharField(default='false', max_length=20)),
                ('profile_image', models.ImageField(upload_to='uploads/')),
                ('employee_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
