# Generated by Django 4.0.5 on 2022-06-24 04:46

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_employee_delete_student_delete_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(upload_to=face.models.upload_to),
        ),
    ]
