# Generated by Django 3.1 on 2022-06-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0013_rename_is_check_in_employee_check_in_and_more'),
        ('face', '0002_alter_employee_profile_image_1_and_more'),
    ]

    operations = [
    ]
